### ISSUE TITLE
Article displays blank

### ISSUE THREAD

**Issue by Joshndroid** [BrightDV/BoxBox#107]
[ARTICLE PART] Hey @BrightDV This link doesn't want to load and just shows a grey/blank screen. The article headline plays nicely in the header section and scrolls but the article area is blank. The article opens just fine in Web browser. Cheers for the cool app

**Article's id**: not sure what this is? 

https://www.formula1.com/en/latest/article.horner-praises-extremely-competitive-testing-showing-from-ricciardo-ahead-of.4xvA88hJSPwGFej6JDpYQp.html

Latest article

![Screenshot_20230713-153154~(1).jpg](https://github.com/BrightDV/BoxBox/assets/5584652/f9190b23-a7ef-4f7a-aa01-ba4ab22b1719)

**Comment by BrightDV** [comment]
Thanks for the issue, it should be fixed in the next version.
It seems that it is the header which is causing the bug, an image gallery. I thought it was supported by the app, but I either guessed wrong, or they have updated the article part…
![image of the json response](https://github.com/BrightDV/BoxBox/assets/92821484/677bae37-a032-4487-a583-f035c69ac745)
> Article's id: not sure what this is?

No worries, here it is `4xvA88hJSPwGFej6JDpYQp`.
 I can find the full article only with its id, but as it is present in the URL, it is fine too.

**Comment by Joshndroid** [comment]
Thanks mate.
Great app so keep up the awesome work 👍
