### ISSUE TITLE
F-Droid version isn't updated

### ISSUE THREAD

**Issue by symbuzzer** [BrightDV/BoxBox#132]
Same as title. Or can u provide built-in app updater feature?

**Comment by BrightDV** [comment]
The F-Droid build is always delayed, because they build the app from source themselves. You have to wait between 3 and 5 days after a release. If you want it just when it is released, you can try [Obtainium](https://github.com/ImranR98/Obtainium) which is excellent at doing it!
Also, see [this comment,](https://github.com/BrightDV/BoxBox/issues/1#issuecomment-1260507565) which made me remove the built-in update notifier.

**Comment by symbuzzer** [comment]
@BrightDV Sir f-droid version is still 0.7.0 and some functions not work properly :( Can you do anything for this?

**Comment by BrightDV** [comment]
It juste have been updated.
I can't make F-Droid's builds faster, but I think that having a custom F-Droid repo for the app might be useful.
