### ISSUE TITLE
Offline capability (videos, audio, news, etc.) when connection lacks

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#155]
Use case: the internet connection lacks for any reason (airplane mode included).

Box, box automatically downloads only the heavy data (for example videos) that I effectively seen: news data are always got because they are light.

Optionally you could adding an on/off switch in settings for this feature.

![1000109728](https://github.com/BrightDV/BoxBox/assets/113377431/9031c623-933c-49ea-852a-afb7ebe9a693)

**Comment by BrightDV** [comment]
So you mean: downloading a video for a future watching or caching the whole video while watching it in case of an internet connection error? 
The first case could be a really nice feature to add (dedicated section with video/article saves), the second one could be easily added with a setting to choose the cache size (in seconds) of the video player.

**Comment by BrightDV** [comment]
> "Caching the whole video while watching" always, even if connection is excellent.

That should be doable. I limited the cache to ~30 seconds because the player can lag (crash?) on devices without a lot of RAM.

> This idea is taken from another app, called ViMusic (fdroid). It put aside (for future offline use) all that I listen, even mistakenly.
> 
> Do you want delete an already downloaded music track?
> 
> Go to "download" tab and delete what you want.
> 
> To do this please add a download "folder" limit, for example max 5 gb or max 3 months, or a combination of both, in order to not consume excessive resources.

I agree for the music player, but is it really useful for a video player? For example, you can listen to a music several times, but I don't guess that you would watch the same video more than 3 to 4 different times (and offline).

> News download all. They are few megabytes (pictures and audio included).

That's seems a good idea, I will see how I can implement it (images and text first).

> What you mean is even another feature, that we can calling "favorites" section or "archive" section.
>
> An user can going on a video and then push "send to archive" or "add to favorites".

Yes, that was the idea; I will open different issues to track the progress of the features' implementation.

**Comment by BrightDV** [comment]
> > I agree for the music player, but is it really useful for a video player? For example, you can listen to a music several times, but I don't guess that you would watch the same video more than 3 to 4 different times (and offline).
> 
> My approach is different: in my idea I haven't to think about anything. Download just happen automatically.
> 
> In your approach you have to push physically the "download" button, and what if the connection lack when you return to see that video again?

Yes: you download a video for a future use, but you need to tap on the download button. Then you can watch it later. 

> Or maybe both the ideas "automatically" (caching) and "watch later".
>
> > I limited the cache to ~30 seconds because the player can lag (crash?) on devices without a lot of RAM.
> 
> We can adding an on/off full caching switch (for less gifted devices).

I think I will add a setting to manually set the cache time, so you would be able to set it to 1 hour.

The point that I want to understand is whether the video should still be available, even after closing the player or the app.
The cache is only used when you are watching the video, like ViMusic does. However, ViMusic keeps the file in the storage after the playing, so you can listen later to the song, but Box, Box! deletes the cache when you exit the player.
The download should save the video in the storage.

My point is that with your approach, all the videos you have seen will be saved on your device, but you may only watch a few of them again.
With a download, you only save offline what you want to see.

For example, when you see a post-race interview of a particular driver, you will not watch it a lot of time. However, race highlights may be saved. That's why a non-automatic approach seems the best to me.

**Comment by BrightDV** [comment]
Ok, that's seems to be the best solution. I will add different settings to that.
Now it is the harder part, because I have to implement a download system ;)

**Comment by BrightDV** [comment]
So here are some screenshots of the download component:
- Download screen (running downloads can be paused, resumed; downloads can be opened, deleted...)
<img src="https://github.com/BrightDV/BoxBox/assets/92821484/0eaa14cc-8859-4000-926e-7b7a88d9fe75" height="400">

- Notification with a progress indicator for the running downloads, and another notification on download finish.
<img src="https://github.com/BrightDV/BoxBox/assets/92821484/6ac17bb5-daae-40a2-a8df-633671bd57ed" width="400">

- There is a new icon on the top right to download/delete an article/video. You can refresh/delete an article; select video quality on download.
<img src="https://github.com/BrightDV/BoxBox/assets/92821484/81674913-f045-4712-9c01-0da2a1064217" height="400">

- Finally, I have added an option in the player to download a video from there (with quality selector also).

**Comment by BrightDV** [comment]
So I just merged the PR!
If you want, you can try the debug build (when I fix the workflow), but if so, you will have to delete your already installed app.

**Comment by BrightDV** [comment]
You have to be logged in to be able to download the file.

> PS: what does it mean "debug" version?

Here I am wrong because it is more a prereleae than a debug version. Anyway, the debug version is a version of the app which logs everything while active, so it is very useful to find bugs, add new features... but not made for production/public releases.
