### ISSUE TITLE
America's Cup Louis Vuitton app request to the developer

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#174]
I love this sport.

Might you develop in the future this app like Box,Box! for sailing?

Official website:

https://www.americascup.com/

The official YouTube channel

All videos:

https://www.youtube.com/channel/UCo15ZYO_XDRU9LI30OPtxAg

Teams presentation:

https://www.youtube.com/playlist?list=PL0sllUFB3RvBOxp2wnC-uBS4ure6sxRRB

**Comment by BrightDV** [comment]
Thanks for the nice suggestion.
Firstly, I have to say that I have no plan to do this anytime soon. I already don't have that much time to fix bugs in Box, Box!, so I don't have any time to create another app alongside.
Also, the formats of the cups doesn't seem to fit in the architecture of Box, Box!, so I can't add it like Formula E neither.
Otherwise, an open-source app about America's cup would be good.

**Comment by BrightDV** [comment]
I guess it means the rounds of the race. I'm not pretty sure, but I searched a bit and in football, it refers to two teams playing against each other two times (leg 1 and 2), and the winner is the team which scored the most goals.
