### ISSUE TITLE
Android Scrolling screenshot does not work in the app

### ISSUE THREAD

**Issue by bagajohny** [BrightDV/BoxBox#27]
- [ ] I use the latest GitHub release of the app.

**Describe the bug**
Scrolling screenshot option does not show up when you take a screenshot in the app.

**Expected behavior**
Ideally "Capture More" option should be available as below

<a href="https://ibb.co/bNKkpky"><img src="https://cdn.nerdschalk.com/wp-content/uploads/2021/07/scrolling-screenshot-on-android-12-2-a.png?width=800" alt="image" border="0"></a>

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: A12

**Comment by BrightDV** [comment]
<img width= "400px" src="https://user-images.githubusercontent.com/92821484/203854890-b7a81bc6-61ec-4a52-b0a3-043039754fba.png"/>

Weird, it works well on my side...

**Comment by sinfullad** [comment]
Could be a Google thing, since I can also scroll screenshot as well on my Samsung

**Comment by BrightDV** [comment]
The problem is that [Google use a different way for taking screenshots: it takes first an entire screenshot and then crop it](https://9to5google.com/2021/07/14/android-12-scrolling-screenshots-pixel/). Sadly, at the moment, the way the application is made does not allow it and for the moment I don't know any workaround..
